apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: mystore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: mystore
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
  namespace: mystore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:v1.12
          ports:
            - containerPort: 7700
          env:
            - name: MEILI_ENV
              value: production
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: mystore-secrets
                  key: MEILISEARCH_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch
  namespace: mystore
spec:
  selector:
    app: meilisearch
  ports:
    - port: 7700
      targetPort: 7700
