<?php

namespace App\Http\Controllers\Concerns;

use Illuminate\Validation\Rule;

trait HasProductRules
{
    protected function productRules(): array
    {
        return [
            'name' => 'required|string',
            'description' => 'nullable|string',
            'short_description' => 'nullable|string',
            'status' => 'nullable|string|in:draft,published,pending',
            'mystore_product_id' => ['nullable', 'string', 'max:255', Rule::unique('products', 'mystore_product_id')->ignore(request()->route('id'))],
            'featured_image' => 'nullable|string|max:2048',
            'gallery_images' => 'nullable|array',
            'gallery_images.*' => 'nullable|string|max:2048',
            'manufacturer' => 'nullable|string|max:255',
            'model_number' => 'nullable|string|max:255',
            'country_of_origin' => 'nullable|string|max:100',
            'product_type' => 'nullable|string|max:120',
            'product_type_keyword' => 'nullable|string|max:255',
            'target_gender' => 'nullable|string|max:80',
            'recommended_age' => 'nullable|string|max:120',
            'condition' => 'nullable|string|in:new,renewed,used_like_new,used_good,used_acceptable,open_box,refurbished',
            'fulfillment_channel' => 'nullable|string|max:120',
            'fulfillment_channels' => 'nullable|array',
            'fulfillment_channels.*' => 'nullable|string|max:120',
            'regular_price' => 'required|numeric',
            'sale_price' => 'nullable|numeric',
            'tax_status' => 'nullable|string|in:taxable,none',
            'tax_class' => 'nullable|string|in:standard,inclusive,exclusive',
            'sku' => 'nullable|string',
            'parent_sku_id' => 'nullable|string|max:120',
            'manage_stock' => 'boolean',
            'stock_quantity' => 'integer',
            'brand_id' => 'nullable|integer',
            'categories' => 'nullable|array',
            'new_category_name' => 'nullable|string|max:255',
            'new_category_parent_id' => 'nullable|integer|exists:categories,id',
            'warehouse_id' => 'nullable|integer',
            'warehouse_qty' => 'nullable|integer',
            'bin_location' => 'nullable|string',
            'safety_stock' => 'nullable|integer|min:0',
            'unit_cost' => 'nullable|numeric|min:0',
            'type' => 'nullable|string|in:simple,variable,variation,grouped,external',
            'parent_id' => 'nullable|integer|exists:products,id',
            'attributes' => 'nullable|array',
            'variations' => 'nullable|array',
            'grouped_product_ids' => 'nullable|array',
            'grouped_product_ids.*' => 'nullable|integer|exists:products,id',
            'external_url' => 'nullable|url|max:2048',
            'external_button_text' => 'nullable|string|max:120',
            'weight_kg' => 'nullable|numeric|min:0',
            'length_cm' => 'nullable|numeric|min:0',
            'width_cm' => 'nullable|numeric|min:0',
            'height_cm' => 'nullable|numeric|min:0',
            'package_weight_kg' => 'nullable|numeric|min:0',
            'package_length_cm' => 'nullable|numeric|min:0',
            'package_width_cm' => 'nullable|numeric|min:0',
            'package_height_cm' => 'nullable|numeric|min:0',
            'bullet_points' => 'nullable|array',
            'bullet_points.*.title' => 'nullable|string|max:120',
            'bullet_points.*.value' => 'nullable|string|max:1000',
            'size_chart' => 'nullable|array',
            'safety_compliance' => 'nullable|array',
            'seo_search_terms' => 'nullable|array',
            'seo_search_terms.*' => 'nullable|string|max:120',
            'whats_inside_box' => 'nullable|array',
            'whats_inside_box.*' => 'nullable|string|max:255',
            'tags' => 'nullable|array',
            'tags.*' => 'nullable|string|max:80',
            'menu_order' => 'nullable|integer',
        ];
    }
}
